@startsalt Рабочий стол водителя
{
    <b>Рабочий стол водителя
    [Принять товар для отправки]
    [Принять товар для утилизации]
}
@endsalt

https://www.plantuml.com/plantuml/png/ZS_12G8n50JGUwhuXOXi7-9XHM_YmSrDX3M2NeGjGKk8eXWDnXPcEdBi81_29yERmsywtwvzrowzuOA8AmgFI7WPTmmeo8QRrXr9tmSo1xTnfXdDnjKDqqnmPY_tuS30ar5MCB8tMIb3KVOLYihVIDFA7lSC0bdlgVoWhUxMDOlL_7_P3m00