@startsalt Рабочий стол владельца
{
    <b>Рабочий стол владельца
    [Посмотреть отчет по остаткам товара]
    [Составить отчет по доходам]
}
@endsalt

https://www.plantuml.com/plantuml/png/bOyn2i9044NxFSKUH2Jta1GHxSJ2f1F113HDxg3UO0m9H1FMAxovaJkWdOq3y-73l0UJv4MsA_9iKtYk27U2rWmyl9PQ4HWzBID2Hy-eZPuHjtS-pcmv_uCnOi65e2LJp4gFz34RZvNQYkT5i6uUYVj4cBn9QP58IFeHtRvNj0o_DHr1JmGwawJku9BrTcMllW40